### ISSUE TITLE
Show current time in the app

### ISSUE THREAD

**Issue by Hydro8** [klimeryk/garmodoro#10]
Hi

I'm using your app on my vivoactive 3, it work great ! Thank for your work !

I don't know if I don't use your app well but I'm facing some problems and maybe you have a workaround.

- Is it possible to show actual time during a pomodoro / resting timer ?
- Is it possible to exit app (with button or gesture) and be back at the right moment ? For example, I want to use my watch during resting time but as soon as I exit the app, I lost progression and timer.

Thank again for your work.

**Comment by klimeryk** [comment]
> Is it possible to show actual time during a pomodoro / resting timer ?

Technically, yes, but on my watch (Fenix 3 HR), it's possible to put the app in background and go back to the watchface, so I did not implement this feature as it'd duplicate the much more robust and helpful default watchface.

> Is it possible to exit app (with button or gesture) and be back at the right moment ? For example, I want to use my watch during resting time but as soon as I exit the app, I lost progression and timer.

I think it depends on the device - on my, it takes a long press of the down button, if I remember correctly. But on a FR735XT I was not able to do so.
As mentioned above, I'd prefer to keep it simple and not clutter the interface with additional fields. Though I agree that if there's no other way to see the clock, an embedded one might be a great improvement 👍

**Comment by klimeryk** [comment]
Current time is now always displayed as of 1.5.0 - enjoy!
