### ISSUE TITLE
feature: save finished pomodoro to garmin connect

### ISSUE THREAD

**Issue by mickeydonkey** [klimeryk/garmodoro#12]
I suggest each pomodoro is saved as custom workout.

**Comment by klimeryk** [comment]
Hi, @mickeydonkey! Good suggestion - when creating the first version of the app, I was going to implement exactly what you propose. But upon more reading, I realized it might not be a good fit. A Pomodoro is not a workout per se, so it's a bit cumbersome to try to save it as such - there are no laps, etc. I'd have to save the number of pomodoro sessions, for example, as a custom field. If I remember correctly, it was not possible to show those custom fields in Garmin Connect, so the data would not be displayed in a meaningful way.
Ultimately, I figured it's not worth the effort and gave up on the whole idea.

Hope this make sense - if I'm wrong about something (like how to make a custom workout show up in Garmin Connect), I'd love to be proven wrong! 🙌
