### ISSUE TITLE
Add the Garmin Descent G1 to the List of Supported Devices

### ISSUE THREAD

**Issue by Genei180** [klimeryk/garmodoro#28]
Please add the Garmin Descent G1 to the Supported List.
In theory, it should have the same watch face as the Garmin Instinct 2 and shouldn't make a lot of extra work.

It would be a real blessing.
Thanks for your Work

**Comment by klimeryk** [comment]
Hi!
Glad you like the app! Sorry for the late follow-up - sometimes hard to keep up with Garmin's new releases. I've just released [version 1.9.1](https://github.com/klimeryk/garmodoro/commit/5f4625b9490792ecc551aea55f90c5b4a5e7fa4e) that adds support for a bunch of new devices, including Garmin Descent G1. Hope it works well for you!
