### ISSUE TITLE
Changing PomodoroLength from Source breaks timer

### ISSUE THREAD

**Issue by boomerAndy** [klimeryk/garmodoro#29]
I tend to do 50 minute pomodoros, and wanted to see if I could use this app but change the length 'pomodoroLength' and 'shortBreakLength' in properties.XML as seen [here](https://github.com/boomerAndy/garmodoro-me/commit/261135698b5937afacf86d23af429d1a5eb13666). 

It seems that making this change breaks the timer in the app on my Garmin device, as it is stuck indefinitely on 25 minutes left. Is there a separate hard-coded integer in the code that needs to be changed to fix this? Appreciate this app exists BTW, I just find scheduling 50+10 minutes much more appealing. Thanks!

**Comment by klimeryk** [comment]
The values in the XML file are the default ones. I'm not sure what's your exact setup (running locally or on your watch), but it's possible the settings have already been seeded by these default values so it's not picking up the new defaults.

There's no need to modify the XML file - you can use Garmin Connect app to configure the settings from there (the settings page is generated based on that XML file). See https://apps.garmin.com/settingsHelp for more info.
