### ISSUE TITLE
I cannot stop the 5 minutes break/rest

### ISSUE THREAD

**Issue by albertomota-codes** [klimeryk/garmodoro#31]
First thanks for working on this app. 
I love it.

I found an area that may make your app more adopted.

Imagine this scenario:

1) Start studying for 25 minutes
2) the 5 min break start, but you need to finish something that will take you 2 min. 

There is no way to decide when the Break start, it simply start inmeadiatly.

I know you may be really  busy. 

Let me know, if I can cooperate donating a cup of cofee, or if you have 30 min for a video call to give me some code pointer, I will be happy to fix it myself.

**Comment by klimeryk** [comment]
Thanks for the kind words and sharing your feedback!

However, I'd say this is a feature, not a bug. Based on my understanding of the Pomodoro Technique: you want to protect one Pomodoro (25 minutes by default) for full focus mode. If there's something left in the current task after those 25 minutes, no matter how tempting, IMHO, you should _stop_, stand up, take a break and come back to it in the next Pomodoro. Either you'll feel more motivated to get back in ("I want to finish it, I'm so close!"), or the break and stretching/whatever will help you realize that maybe you missed something, there's more to do, etc.

I understand that might not always work for everyone (we all have different quirks and approaches), but that's how the app has been designed to nudge folks to work 🙇
