### ISSUE TITLE
Allow toggling sounds from in-app settings

### ISSUE THREAD

**Issue by klimeryk** [klimeryk/garmodoro#6]
The sound effects are controlled by your global sound settings - so if you've muted your sounds globally, this app will respect that, of course. But it might be better to have a more fine-grained control and some users might prefer to keep sounds enabled (for other activities), while the sounds in the Pomodoro app to be disabled (because they want to use it in a library, etc.).

**Comment by boos** [comment]
I second this option, I work in an open space and I don't want my phone to beep every time while I still want to turn on the global sound settings. Could you make it configurable?

I am not using the app just for this reason.

**Comment by klimeryk** [comment]
Fixed by https://github.com/klimeryk/garmodoro/commit/ec2d0170b3c2561f6287085306f794fa828fc549 🎉
