### ISSUE TITLE
Show seconds

### ISSUE THREAD

**Issue by diskostu** [klimeryk/garmodoro#7]
I'd like to see the seconds in addition to the minutes. Thanks! Great app :-)

**Comment by klimeryk** [comment]
Thanks - noted. Though, I must admit it will be low priority for me, because I just don't see the need for being precise to the second here (just like real pomodoro does not show seconds, just minutes).

**Comment by klimeryk** [comment]
Closing this as wontfix - I don't see seconds as valuable information in this context, plus it requires updating the watch every second which will negatively impact battery life.
