### ISSUE TITLE
Too many "tick" vibration after pressing START

### ISSUE THREAD

**Issue by hoangdj** [klimeryk/garmodoro#8]
Hi klimeryk, I'm using garmodoro on Fenix 3, and after pressing START, I feel like I've had a new heart on my wrist, as the app keep vibrating on and on. I tried to disable it by setting 0 for either strength and duration but it said "invalid value"

**Comment by klimeryk** [comment]
It should be a valid value for strength - have you tried changing _just_ that option? (it is _not_ a valid value for the duration one)

**Comment by klimeryk** [comment]
PS: more context on the ticking: https://github.com/klimeryk/garmodoro/issues/1#issuecomment-331624926
