### ISSUE TITLE
 A Bug ,please fix ASAP!

### ISSUE THREAD

**Issue by Fasterjie** [klimeryk/garmodoro#9]
Thanks for your good work. The 1.2.0 version went on pretty well, until yesterday I update to 1.3.0, the App was crashed and my devise was power off and start again every time when I restart or exit this app. Please fix this bug ASAP, my devise is fenix 3HR.

**Comment by klimeryk** [comment]
Thanks for the report, @Fasterjie - I'll investigate ASAP.

**Comment by klimeryk** [comment]
Unfortunately, it's not something I can fix, it's a bug in the watch's firmware: https://forums.garmin.com/forum/developers/connect-iq/connect-iq-bug-reports/1271079-device-crash-err_log-txt-fenix-3-hr-sw-ver-430-450

Will report here when it's fixed. Seems a beta version of the firmware has a fix for it and it should be available to all soon.

**Comment by klimeryk** [comment]
Closing as it looks like 4.60 fixes the issue.
